name: myapp
description: A new Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"  # Ajuste para a versão que você usa

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
